// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IJM3Wd_EN9DTGx14mA-WYl20xwSonzU',
    appId: '1:415681166117:web:50564ed936d1f4ed47b8cc',
    messagingSenderId: '415681166117',
    projectId: 'fir-77fcd',
    authDomain: 'fir-77fcd.firebaseapp.com',
    storageBucket: 'fir-77fcd.appspot.com',
    measurementId: 'G-8V2GB74472',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB150Ofe-7Y_kjmnI_CuFbBHEzVRvkxxDY',
    appId: '1:415681166117:android:bb5d12caf07e9f5247b8cc',
    messagingSenderId: '415681166117',
    projectId: 'fir-77fcd',
    storageBucket: 'fir-77fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LiMLy2He1f7CKsPAzIRDLcpIn-5sRAM',
    appId: '1:415681166117:ios:5bf22b4f199030d647b8cc',
    messagingSenderId: '415681166117',
    projectId: 'fir-77fcd',
    storageBucket: 'fir-77fcd.appspot.com',
    iosBundleId: 'com.example.expenzeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LiMLy2He1f7CKsPAzIRDLcpIn-5sRAM',
    appId: '1:415681166117:ios:5bf22b4f199030d647b8cc',
    messagingSenderId: '415681166117',
    projectId: 'fir-77fcd',
    storageBucket: 'fir-77fcd.appspot.com',
    iosBundleId: 'com.example.expenzeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8IJM3Wd_EN9DTGx14mA-WYl20xwSonzU',
    appId: '1:415681166117:web:763c3cf4f9037a0147b8cc',
    messagingSenderId: '415681166117',
    projectId: 'fir-77fcd',
    authDomain: 'fir-77fcd.firebaseapp.com',
    storageBucket: 'fir-77fcd.appspot.com',
    measurementId: 'G-NGJZJWCKQ5',
  );
}
